export const monsters = [
  {
    name:'Rathalos',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img76.png'
  },
  {
    name:'Tigrex',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img34.png'
  },
  {
    name:'Zinogre',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img28.png'
  },
  {
    name:'Devil Jho',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img07.png'
  },
  {
    name:'Kushala Daora',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img17.png'
  },
  {
    name:'Glavenus',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img37.png'
  },
  {
    name:'Nargacuga',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img47.png'
  },
  {
    name:'Teostra',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img38.png'
  },
  {
    name:'Brachydios',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img59.png'
  },
  {
    name:'Nergigante',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img49.png'
  },
  {
    name:'Rajang',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img69.png'
  },
  {
    name:'Lagiacrus',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img71.png'
  },
  {
    name:'Diablos',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img32.png'
  },
  {
    name:'Bazelgeuse',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img55.png'
  },
  {
    name:'Congalala',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img56.png'
  },
  {
    name:'Nerscylla',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img50.png'
  },
  {
    name:'Kirin',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img15.png'
  },
  {
    name:'Gammoth',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img13.png'
  },
  {
    name:'Anjanath',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img04.png'
  },
  {
    name:'Zamtrios',
    img:'https://www.monsterhunter.com/wp-content/uploads/sites/3/2021/09/mhst2_monster_icon_img27.png'
  },
];